### ISSUE TITLE
How can we avoid vite config ssl secret ending up on github

### ISSUE THREAD

**Issue by mfsbo** [AlexJPotter/.NET-6-and-Vue-3-sample-app#1]
Thanks for the post and git repo for doing this.

https://github.com/AlexJPotter/.NET-6-and-Vue-3-sample-app/blob/e8004b405b14278502fcbaba64f8e09cfd020ceb/ClientApp/vite.config.ts#L12

The above line seems to be there because of SSL setup for Vite. 
Can we not put this in another file and load from there in vite config and ignore that file so each dev in team can have their own secret exported from sslsecret.ts file or something.  If you have solved it already in different way please share.

**Comment by AlexJPotter** [comment]
Hi @mfsbo - you are free to choose your own passphrase for the exported `.pfx` file and store that in a separate file or environment variable. The certificate is only a developer certificate for `localhost`, so the tangible risk is very low, but there's no reason why you can't make it more secure if you have specific security concerns.

A reminder that a full walkthrough of how the repo was put together can be found on my blog:
https://alexpotter.dev/net-6-with-vue-3/
